### numpy

#### np.mean(), np.median(), np.var(), np.std()
##### axis=0 - per column, axis=1 - per row

In [2]:
import numpy as np

In [4]:
dataset = np.genfromtxt('normal_distribution.csv', delimiter=',')  # load data with numpy genfromtxt

In [5]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [6]:
dataset.shape

(24, 8)

In [7]:
np.mean(dataset[0])  # calculate mean of first row

100.177647525

In [8]:
np.mean(dataset[:, 0])  # calculate mean of first column

99.76743510416668

In [9]:
np.mean(dataset, axis=1)  # calculate mean of each row using axis

array([100.17764752,  97.27899259, 100.20466135, 100.56785907,
       100.98341406,  97.83018578, 101.49052285,  99.75332252,
       101.89845125,  99.77973914, 101.013081  , 100.54961696,
        98.48256886,  98.49816126, 101.85956927,  97.05201872,
       102.62147483, 101.21177037,  99.58777968,  98.96533534,
       103.85792812, 101.89050288,  99.07192574,  99.34233101])

In [10]:
np.mean(dataset, axis=0)  # calculate mean of each column using axis

array([ 99.7674351 ,  99.61229127, 101.14584656, 101.8449316 ,
        99.04871791,  99.67838931,  99.7848489 , 100.44049274])

In [11]:
np.mean(dataset)

100.16536917390624

In [12]:
dataset[0:2]  # print first two rows

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

In [13]:
np.mean(dataset[2])

100.20466135250001

In [14]:
np.mean(dataset[:, -1])

100.4404927375

In [15]:
np.mean(dataset[:3,:3])

97.87197312333333

In [16]:
np.median(dataset[-1])

99.18748092

In [17]:
np.median(dataset[:, -3:])

99.47332349999999

In [18]:
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [19]:
np.var(dataset[-2:,:2])

4.674691991769191

In [20]:
np.std(dataset)

4.838197554269257

#### splitting

In [21]:
np.hsplit(dataset, (2))  # split horizontally in 2 equal parts

[array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675],
        [ 92.02628776,  97.10439252,  99.32066924,  97.24584816],
        [ 95.66253664,  95.17750125,  90.93318132, 110.18889465],
        [ 91.37294597, 100.96781394, 100.40118279, 113.42090475],
        [101.20862522, 103.5730309 , 100.28690912, 105.85269352],
        [102.80387079,  98.29687616,  93.24376389,  97.24130034],
        [106.71751618, 102.97585605,  98.45723272, 100.72418901],
        [ 96.02548256, 102.82360856, 106.47551845, 101.34745901],
        [105.30350449,  92.87730812, 103.19258339, 104.40518318],
        [110.44484313,  93.87155456, 101.5363647 ,  97.65393524],
        [101.3514185 , 100.37372248, 106.6471081 , 100.61742813],
        [ 97.21315663, 107.02874163, 102.17642112,  96.74630281],
        [ 95.65982034, 107.22482426, 107.19119932, 102.93039474],
        [100.39303522,  92.0108226 ,  97.75887636,  93.18884302],
        [103.1521596 , 109.40523174,  93.83969256,  99.95827854],
        [1

### splitting 

In [22]:
np.vsplit(dataset, (2))  # split vertically in 2 equal parts

[array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
          98.74986914,  98.80833412,  96.81964892,  98.56783189],
        [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
          92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
        [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
          98.80084371, 105.95297652,  98.37481387, 106.54654286],
        [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
         105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
        [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
          93.37126331, 108.57980357, 100.79478953,  94.20019732],
        [102.80387079,  98.29687616,  93.24376389,  97.24130034,
          89.03452725,  96.2832753 , 104.60344836, 101.13442416],
        [106.71751618, 102.97585605,  98.45723272, 100.72418901,
         106.39798503,  95.46493436,  94.35373179, 106.83273763],
        [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
         102.45651

In [23]:
np.hsplit(dataset, (2))  # split horizontally in 2 equal parts

[array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675],
        [ 92.02628776,  97.10439252,  99.32066924,  97.24584816],
        [ 95.66253664,  95.17750125,  90.93318132, 110.18889465],
        [ 91.37294597, 100.96781394, 100.40118279, 113.42090475],
        [101.20862522, 103.5730309 , 100.28690912, 105.85269352],
        [102.80387079,  98.29687616,  93.24376389,  97.24130034],
        [106.71751618, 102.97585605,  98.45723272, 100.72418901],
        [ 96.02548256, 102.82360856, 106.47551845, 101.34745901],
        [105.30350449,  92.87730812, 103.19258339, 104.40518318],
        [110.44484313,  93.87155456, 101.5363647 ,  97.65393524],
        [101.3514185 , 100.37372248, 106.6471081 , 100.61742813],
        [ 97.21315663, 107.02874163, 102.17642112,  96.74630281],
        [ 95.65982034, 107.22482426, 107.19119932, 102.93039474],
        [100.39303522,  92.0108226 ,  97.75887636,  93.18884302],
        [103.1521596 , 109.40523174,  93.83969256,  99.95827854],
        [1

### iterating
#### np.nditer(...), np.ndenumerate(...)

In [25]:
dataset2 = np.genfromtxt('normal_distribution_splittable.csv', delimiter=',')

In [26]:
dataset2

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189,
        101.34745901],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942,
         93.87155456],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286,
        107.22482426],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803,
        103.40412146],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732,
         96.10020311],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416,
         97.62787811],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.4649

In [27]:
second_row = dataset2[1]
np.mean(second_row)

96.90038836444445

In [28]:
last_row = dataset2[-1]
np.mean(last_row)

100.18096645222221

In [29]:
first_val_first_row = dataset2[0][0]
np.mean(first_val_first_row)

99.14931546

In [30]:
every_other_elem = dataset2[4, ::2]
np.mean(every_other_elem)

98.35235805800001

In [31]:
index = 0
for x in np.nditer(dataset2):
    print(x, index)
    index += 1

99.14931546 0
104.03852715 1
107.43534677 2
97.85230675 3
98.74986914 4
98.80833412 5
96.81964892 6
98.56783189 7
101.34745901 8
92.02628776 9
97.10439252 10
99.32066924 11
97.24584816 12
92.9267508 13
92.65657752 14
105.7197853 15
101.23162942 16
93.87155456 17
95.66253664 18
95.17750125 19
90.93318132 20
110.18889465 21
98.80084371 22
105.95297652 23
98.37481387 24
106.54654286 25
107.22482426 26
91.37294597 27
100.96781394 28
100.40118279 29
113.42090475 30
105.48508838 31
91.6604946 32
106.1472841 33
95.08715803 34
103.40412146 35
101.20862522 36
103.5730309 37
100.28690912 38
105.85269352 39
93.37126331 40
108.57980357 41
100.79478953 42
94.20019732 43
96.10020311 44
102.80387079 45
98.29687616 46
93.24376389 47
97.24130034 48
89.03452725 49
96.2832753 50
104.60344836 51
101.13442416 52
97.62787811 53
106.71751618 54
102.97585605 55
98.45723272 56
100.72418901 57
106.39798503 58
95.46493436 59
94.35373179 60
106.83273763 61
100.07721494 62
96.02548256 63
102.82360856 64
106.475518

In [32]:
for index, value in np.ndenumerate(dataset2):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(0, 8) 101.34745901
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(1, 8) 93.87155456
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(2, 8) 107.22482426
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(3, 8) 103.40412146
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(4, 8) 96.10020311
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.6034

## Filtering, Sorting

In [33]:
dataset3 = np.genfromtxt('normal_distribution_splittable.csv', delimiter=',')
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

### Filtering
#### dataset[dataset > ...], np.extraxt((dataset > ...) & (dataset < ...)), np.where

In [34]:
values_greater_105 = dataset[dataset > 105]
values_greater_105

array([107.43534677, 105.7197853 , 110.18889465, 105.95297652,
       106.54654286, 113.42090475, 105.48508838, 106.1472841 ,
       105.85269352, 108.57980357, 106.71751618, 106.39798503,
       106.83273763, 106.47551845, 105.30350449, 106.03868807,
       110.44484313, 106.6471081 , 105.0320535 , 107.02874163,
       105.07475277, 107.22482426, 107.19119932, 108.09423367,
       109.40523174, 106.11454989, 106.57052697, 105.13668343,
       105.37011896, 105.86078488, 106.89005002, 106.57364584,
       107.40064604, 106.38276709, 106.46476468, 110.43976681,
       105.02389857, 106.05042487])

In [35]:
values_between_90_95 = np.extract((dataset > 90) & (dataset < 95), dataset)
values_between_90_95

array([92.02628776, 92.9267508 , 92.65657752, 90.93318132, 91.37294597,
       91.6604946 , 93.37126331, 94.20019732, 93.24376389, 94.35373179,
       92.5748759 , 92.87730812, 93.87155456, 92.75048583, 91.32093303,
       92.0108226 , 93.18884302, 93.83969256, 94.5081787 , 94.59300658,
       93.04610867, 91.6779221 , 94.76253572, 94.57421727, 94.11176915,
       93.97853495])

In [36]:
rows, cols = np.where(abs(dataset - 100) < 1)
one_away_index = [[rows[index], cols[index]] for (index, _) in np.ndenumerate(rows)]
one_away_index

[[0, 0],
 [1, 2],
 [3, 1],
 [3, 2],
 [4, 2],
 [4, 6],
 [6, 3],
 [8, 5],
 [10, 1],
 [10, 3],
 [10, 5],
 [13, 0],
 [13, 4],
 [13, 7],
 [14, 3],
 [14, 5],
 [16, 1],
 [16, 6],
 [17, 2],
 [17, 3],
 [18, 7],
 [20, 4],
 [21, 0],
 [21, 4],
 [21, 5],
 [22, 2],
 [23, 1],
 [23, 7]]

In [37]:
abs(100 - dataset[23, 7])  # check if correct

0.07721494000000462

### Sorting
#### np.sort, np.argsort

In [38]:
row_sorted = np.sort(dataset)  # last axis by default, i.e. axis=1 (rows)
row_sorted

array([[ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
         98.80833412,  99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  92.65657752,  92.9267508 ,  97.10439252,
         97.24584816,  99.32066924, 101.23162942, 105.7197853 ],
       [ 90.93318132,  95.17750125,  95.66253664,  98.37481387,
         98.80084371, 105.95297652, 106.54654286, 110.18889465],
       [ 91.37294597,  91.6604946 ,  95.08715803, 100.40118279,
        100.96781394, 105.48508838, 106.1472841 , 113.42090475],
       [ 93.37126331,  94.20019732, 100.28690912, 100.79478953,
        101.20862522, 103.5730309 , 105.85269352, 108.57980357],
       [ 89.03452725,  93.24376389,  96.2832753 ,  97.24130034,
         98.29687616, 101.13442416, 102.80387079, 104.60344836],
       [ 94.35373179,  95.46493436,  98.45723272, 100.72418901,
        102.97585605, 106.39798503, 106.71751618, 106.83273763],
       [ 92.5748759 ,  96.02548256,  97.57544275,  98.74767493,
        101.34745901, 102.4565179

In [39]:
col_sorted = np.sort(dataset, axis=0)
col_sorted

array([[ 91.37294597,  88.80221141,  90.93318132,  93.18884302,
         85.98839623,  91.6604946 ,  91.32093303,  92.5748759 ],
       [ 92.02628776,  91.6779221 ,  93.24376389,  94.59300658,
         89.03452725,  92.65657752,  93.04610867,  94.20019732],
       [ 94.11176915,  92.0108226 ,  93.83969256,  96.74630281,
         92.75048583,  95.19184343,  94.35373179,  94.76253572],
       [ 95.65982034,  92.87730812,  94.5081787 ,  97.24130034,
         92.9267508 ,  95.46493436,  96.50342927,  95.08715803],
       [ 95.66253664,  93.87155456,  97.75887636,  97.24584816,
         93.37126331,  95.62359311,  96.81964892,  95.85284217],
       [ 96.02548256,  94.57421727,  98.45723272,  97.62787811,
         93.97853495,  96.2832753 ,  96.89244283,  97.59572169],
       [ 96.10020311,  95.17750125,  99.32066924,  97.65393524,
         95.93799169,  96.34622848,  96.96851209,  98.00253006],
       [ 96.76814836,  96.59385486,  99.57859892,  97.85230675,
         98.29243952,  96.5937781

In [40]:
index_sorted = np.argsort(dataset[0])
dataset[0][index_sorted]

array([ 96.81964892,  97.85230675,  98.56783189,  98.74986914,
        98.80833412,  99.14931546, 104.03852715, 107.43534677])

### Combining
#### np.vstack, np.hstack

### Reshaping
#### np.reshape